# src/services/remediation_service.py
import sys
import os
import re
import difflib
from typing import Dict, Any

from src.models.schemas import IncidentStatus, PipelineStatus
from src.incidents.incident_manager import IncidentManager
from src.services.pipeline_service import PipelineService
from src.services.audit_service import AuditService
from src.config import save_pipeline_config_draft, verify_pipeline_config, delete_pipeline_config_version, get_recovery_config
from src.telemetry.logger import get_pipeline_logger

logger = get_pipeline_logger("remediation_service")

class RemediationService:
    @classmethod
    def validate_fix_schema(cls, pipeline_id: str, params: dict) -> bool:
        """Validates proposed configuration overrides against structural whitelists and injection guards."""
        if not params:
            return False
        recovery_cfg = get_recovery_config()
        allowed_keys = set(recovery_cfg.get("pipelines", {}).get(pipeline_id, {}).get("allowed_params", []))

        def _normalize_text(value: str | None) -> str:
            if not value:
                return ""
            return re.sub(r"[^a-z0-9]", "", value.lower())

        def _best_fuzzy_match(target: str, candidates: set[str], cutoff: float = 0.82) -> str | None:
            if not target or not candidates:
                return None
            normalized_target = _normalize_text(target)
            normalized_candidates = {c: _normalize_text(c) for c in candidates}
            # exact match
            for c, nc in normalized_candidates.items():
                if nc == normalized_target:
                    return c
            # best ratio
            scored = [(difflib.SequenceMatcher(None, normalized_target, nc).ratio(), c) for c, nc in normalized_candidates.items()]
            scored.sort(reverse=True)
            if scored and scored[0][0] >= cutoff:
                return scored[0][1]
            return None

        for key, val in list(params.items()):
            # If allowed_keys is non-empty, ensure key is allowed (or fuzzy-match to an allowed key)
            if allowed_keys and key not in allowed_keys:
                matched = _best_fuzzy_match(key, allowed_keys, cutoff=0.82)
                if matched:
                    # replace param key with matched allowed key for further validation
                    params[matched] = params.pop(key)
                    key = matched
                else:
                    logger.warning("Validation rejected: Key not in allowed parameter whitelist", pipeline_id=pipeline_id, key=key)
                    return False
            
            # Value check: only allow letters, numbers, underscores (valid JSON/CSV column identifier) for Pipeline A
            if pipeline_id != "PIPELINE_B":
                if key == "flatten_root_dict":
                    if not isinstance(val, (bool, str)) or str(val).lower() not in ["true", "false"]:
                        logger.warning("Validation rejected: Invalid boolean for flatten_root_dict", pipeline_id=pipeline_id, value=val)
                        return False
                else:
                    if not isinstance(val, str) or not re.match(r"^[a-zA-Z0-9_]+$", val):
                        logger.warning("Validation rejected: Invalid alphanumeric column identifier", pipeline_id=pipeline_id, value=val)
                        return False
                
            # Injection pattern guards
            if isinstance(val, str):
                lower_val = val.lower()
                injection_patterns = ["drop", "delete", "insert", "update", "union", "duplicate", "truncate", "alter", "grant"]
                # Exclude SELECT check for Pipeline B SQL query string overrides
                if pipeline_id != "PIPELINE_B":
                    injection_patterns.append("select")
                if any(pattern in lower_val for pattern in injection_patterns):
                    logger.warning("Validation rejected: Potential SQL injection signature detected", pipeline_id=pipeline_id, value=val)
                    return False
                
        return True

    @classmethod
    def execute_directive(cls, incident_id: str, pipeline_id: str, run_id: str, directive: Dict[str, Any], source_path: str | None = None) -> None:
        """
        Parses the JSON structure generated by the LangGraph recovery node 
        and maps it to physical system commands.
        """
        if not directive:
            logger.error("No recovery directive found; escalating workflow", incident_id=incident_id)
            IncidentManager.transition_to(incident_id, IncidentStatus.ESCALATED)
            return

        action = directive.get("action", "ESCALATE").upper()
        params = directive.get("params", {})
        error_signature = directive.get("error_signature", "GENERIC")
        
        AuditService.log_event(incident_id, "ACTUATOR", f"Executing remediation strategy: [{action}]")

        if action == "RETRY":
            cls._handle_retry(incident_id, pipeline_id, run_id, params, source_path=source_path)
        elif action == "QUARANTINE":
            cls._handle_quarantine(incident_id, pipeline_id, params)
        elif action == "RECONFIGURE":
            cls._handle_reconfigure(incident_id, pipeline_id, params, error_signature, source_path=source_path)
        elif action == "REPAIR_FILE":
            cls._handle_repair_file(incident_id, pipeline_id, run_id, params, error_signature, source_path=source_path)
        else:
            cls._handle_escalation(incident_id)

    @classmethod
    def _handle_retry(cls, incident_id: str, pipeline_id: str, run_id: str, params: dict, source_path: str | None = None) -> None:
        """Executes a smart infrastructure retry sequence, correcting runtime state."""
        delay = params.get("attempt_delay_seconds", 5)
        logger.info("Initiating automated recovery retry vector", pipeline_id=pipeline_id, delay_seconds=delay)
        
        from src.incidents.incident_repository import IncidentRepository
        incident = IncidentRepository.get_incident(incident_id)
        original_filename = incident.telemetry_metadata.get("original_filename") if incident and incident.telemetry_metadata else None

        # Dynamically import and re-execute the target pipeline class
        try:
            # Map platform names cleanly back to module files
            if pipeline_id == "PIPELINE_A":
                from src.pipeline.json_pipeline import PipelineA
                pipeline_worker = PipelineA()
            elif pipeline_id == "PIPELINE_B":
                from src.pipeline.db_pipeline import PipelineB
                pipeline_worker = PipelineB()
            else:
                raise ImportError("Unknown operational pipeline context target.")

            # Re-execute workload (Healing Verification)
            logger.info("Relaunching workload under clean state parameters", pipeline_id=pipeline_id)
            # If it's a reconfigure or retry, we run it
            if pipeline_id == "PIPELINE_A" and source_path:
                result = pipeline_worker.execute(json_file_path=source_path, original_filename=original_filename, run_id=run_id)
            elif pipeline_id == "PIPELINE_B" and source_path:
                result = pipeline_worker.execute(op_db_path=source_path, original_filename=original_filename, run_id=run_id)
            else:
                result = pipeline_worker.execute(original_filename=original_filename, run_id=run_id)
            
            if result is not None:
                logger.info("Pipeline healed successfully on auto-retry loop", pipeline_id=pipeline_id, run_id=run_id)
                # Mark run as HEALED and close out the tracking incident as RESOLVED
                PipelineService.update_run_status(run_id, PipelineStatus.HEALED)
                IncidentManager.transition_to(incident_id, IncidentStatus.RESOLVED)
                AuditService.log_event(incident_id, "ACTUATOR", "Auto-remediation successful. Workload state reverted to healthy.")
            else:
                raise RuntimeWarning("Retry execution encountered nested secondary failure condition.")
                
        except Exception as e:
            logger.exception("Remediation retry aborted due to nested error", error=str(e))
            cls._handle_escalation(incident_id)

    @classmethod
    def _handle_quarantine(cls, incident_id: str, pipeline_id: str, params: dict) -> None:
        """Simulates isolating bad records to unblock the rest of the ingestion queue."""
        logger.info("Extracting contaminated elements to isolated target table", incident_id=incident_id)
        
        from src.incidents.incident_repository import IncidentRepository
        incident = IncidentRepository.get_incident(incident_id)
        run_id = incident.run_id if incident else None
        
        if run_id:
            PipelineService.update_run_status(run_id, PipelineStatus.HEALED)
            
        IncidentManager.transition_to(incident_id, IncidentStatus.RESOLVED)
        AuditService.log_event(incident_id, "ACTUATOR", "Poisoned data payload isolated. Balance data unblocked.")

    @classmethod
    def _handle_reconfigure(cls, incident_id: str, pipeline_id: str, params: dict, error_signature: str, source_path: str | None = None) -> None:
        """Alters execution environmental properties on-the-fly and reruns to heal."""
        logger.debug("Pre-application security & schema validation check", incident_id=incident_id)
        
        if not cls.validate_fix_schema(pipeline_id, params):
            logger.warning("Proposed configuration rejected during validation; escalating", incident_id=incident_id)
            cls._handle_escalation(incident_id)
            return

        logger.info("Validation successful; persisting draft configuration override", pipeline_id=pipeline_id, incident_id=incident_id)
        draft_version = save_pipeline_config_draft(pipeline_id, error_signature, params)
        logger.info("Draft config saved; running dry-run verification", pipeline_id=pipeline_id, draft_version=draft_version)

        from src.incidents.incident_repository import IncidentRepository
        incident = IncidentRepository.get_incident(incident_id)
        original_filename = incident.telemetry_metadata.get("original_filename") if incident and incident.telemetry_metadata else None
        run_id = incident.run_id if incident else None

        try:
            if pipeline_id == "PIPELINE_A":
                from src.pipeline.json_pipeline import PipelineA
                pipeline_worker = PipelineA()
                if source_path:
                    result = pipeline_worker.execute(json_file_path=source_path, schema_mapping_override=params, throw_on_error=True, original_filename=original_filename, run_id=run_id)
                else:
                    result = pipeline_worker.execute(schema_mapping_override=params, throw_on_error=True, original_filename=original_filename, run_id=run_id)
            elif pipeline_id == "PIPELINE_B":
                from src.pipeline.db_pipeline import PipelineB
                pipeline_worker = PipelineB()
                if source_path:
                    result = pipeline_worker.execute(sql_override=params.get("sql_override"), op_db_path=source_path, original_filename=original_filename, run_id=run_id)
                else:
                    result = pipeline_worker.execute(sql_override=params.get("sql_override"), original_filename=original_filename, run_id=run_id)
            else:
                raise ImportError("Unknown operational pipeline context target.")
                
            if result is not None:
                logger.info("Pipeline dry-run succeeded; committing config version", pipeline_id=pipeline_id, draft_version=draft_version)
                verify_pipeline_config(pipeline_id, error_signature, draft_version)
                IncidentManager.transition_to(incident_id, IncidentStatus.RESOLVED)
                AuditService.log_event(incident_id, "ACTUATOR", f"Configuration version {draft_version} verified. Pipeline auto-remediated and successfully processed {result} records.")
            else:
                raise RuntimeWarning("Dry-run execution returned secondary failure.")
        except KeyError as ke:
            # Parse the new missing key from the error message using the ErrorSignature format
            import re
            error_msg = str(ke)
            match = re.search(r"KeyError\|([^|\]]+)", error_msg)
            new_missing_key = match.group(1) if match else None
            
            # The keys we just resolved (e.g. "customer_id", "user_email")
            resolved_values = list(params.values())
            
            # It is a new error if the new missing key is not one of the keys we just resolved
            is_new_error = True
            if new_missing_key and new_missing_key in resolved_values:
                is_new_error = False
            
            if is_new_error:
                logger.info("Dry-run hit new KeyError indicating original issue resolved; committing override", new_missing_key=new_missing_key, error_signature=error_signature)
                verify_pipeline_config(pipeline_id, error_signature, draft_version)
                IncidentManager.transition_to(incident_id, IncidentStatus.RESOLVED)
                AuditService.log_event(incident_id, "ACTUATOR", f"Configuration version {draft_version} verified (resolved original issue). Committing.")
            else:
                logger.warning("Dry-run failed on same key; rolling back config version", new_missing_key=new_missing_key, draft_version=draft_version)
                delete_pipeline_config_version(pipeline_id, error_signature, draft_version)
                cls._handle_escalation(incident_id)
        except Exception as e:
            logger.exception("Reconfiguration dry-run failed; rolling back config version", error=str(e), draft_version=draft_version)
            delete_pipeline_config_version(pipeline_id, error_signature, draft_version)
            cls._handle_escalation(incident_id)

    @classmethod
    def _handle_repair_file(cls, incident_id: str, pipeline_id: str, run_id: str, params: dict, error_signature: str, source_path: str | None = None) -> None:
        """Uses LLM to repair raw file content anomalies (e.g. malformed JSON syntax)."""
        logger.info("Executing automated LLM file syntax repair...", incident_id=incident_id)
        if not source_path or not os.path.exists(source_path):
            logger.error("Source path not found for file repair", source_path=source_path)
            cls._handle_escalation(incident_id)
            return
            
        from src.config import get_llm_config
        from langchain_google_genai import ChatGoogleGenerativeAI
        from langchain_core.prompts import ChatPromptTemplate
        
        llm_cfg = get_llm_config()
        llm = ChatGoogleGenerativeAI(model=llm_cfg["model_name"], temperature=0.0)
        
        try:
            with open(source_path, "r", encoding="utf-8") as f:
                raw_content = f.read()
                
            prompt = ChatPromptTemplate.from_messages([
                ("system", "You are a JSON syntax repair agent. Your ONLY job is to output the fully repaired raw JSON without any markdown formatting, backticks, or conversational text. The JSON must be syntactically valid."),
                ("human", "Fix the syntax errors in this JSON file:\n{raw_content}")
            ])
            chain = prompt | llm
            response = chain.invoke({"raw_content": raw_content})
            
            fixed_content = response.content.strip()
            
            # Clean up LLM output if it hallucinated markdown formatting
            if fixed_content.startswith("```json"):
                fixed_content = fixed_content.strip("`").replace("json\n", "", 1).strip()
            elif fixed_content.startswith("```"):
                fixed_content = fixed_content.strip("`").strip()
                
            with open(source_path, "w", encoding="utf-8") as f:
                f.write(fixed_content)
                
            logger.info("Successfully repaired JSON file syntax via LLM.", pipeline_id=pipeline_id)
            AuditService.log_event(incident_id, "ACTUATOR", "File syntax repaired successfully by LLM.")
            
            # Execute standard retry flow on the fixed file
            cls._handle_retry(incident_id, pipeline_id, run_id, params, source_path=source_path)
            
        except Exception as e:
            logger.exception("File repair LLM invocation failed", error=str(e))
            cls._handle_escalation(incident_id)

    @classmethod
    def _handle_escalation(cls, incident_id: str) -> None:
        """Fallback routine when automation is exhausted. Routes to human operators."""
        logger.critical("Automated remediation bounds exceeded; escalating to on-call")
        IncidentManager.transition_to(incident_id, IncidentStatus.ESCALATED)
        AuditService.log_event(incident_id, "ACTUATOR", "System automated runbooks exhausted. Incident escalated to human engineering queue.")
        
        try:
            from datetime import datetime, timezone
            from src.incidents.incident_repository import IncidentRepository
            
            timestamp = datetime.now(timezone.utc).isoformat()
            incident = IncidentRepository.get_incident(incident_id)
            error_msg = incident.error_message.replace("\n", " ").strip() if incident and incident.error_message else "Unknown failure reason"
            
            with open("escalated_incidents.log", "a", encoding="utf-8") as f:
                f.write(f"[{timestamp}] Incident: {incident_id} | Reason: {error_msg}\n")
        except Exception as e:
            logger.error("Failed to write to escalations list", error=str(e))
